language: php
php:
  - 5.5
  - 5.6
  - 7
install:
  - composer self-update
  - composer install
before_script:
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console hautelook_alice:doctrine:fixtures:load -n --env=test
script:
  - phpunit --coverage-text
after_success:
  - ./bin/phpcs --standard=psr2 src
  - ./bin/phpmd src text cleancode,codesize,controversial,design,unusedcode
  - ./bin/phpcpd src