services:
    bookmarks.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['BookmarksBundle:Bookmark']

    bookmarks:
        class: BookmarksBundle\Services\BookmarkService
        arguments: ['@doctrine.orm.entity_manager', '@bookmarks.repository']

    comment:
        class: BookmarksBundle\Services\CommentService
        arguments: ['@doctrine.orm.entity_manager']